### ISSUE TITLE
Broadcast of parameter m_StepbyStep is missing

### ISSUE THREAD

**Issue by kdoertel** [HydroBench/Hydro#4]
Issue in Hydro/HydroC/HydroSyclMPI/Domain.cpp.
Broadcast of parameter m_StepbyStep is missing. As a consequence, at line 387 of Domain_Compute.cpp only rank 0 executes the (on GPU faster) function computeTimeStepByStep. All other ranks execute the (on GPU slower) computeTimeStep. The performance goes down for more than 1 MPI rank.

Fix: add broadcast of m_StepbyStep
```
diff -wb ./Domain.cpp.0ri ./Domain.cpp
580a581,582
>         MPI_Bcast(&m_StepbyStep, 1, MPI_CXX_BOOL, 0, MPI_COMM_WORLD);
>
```

**Comment by JCfrW** [comment]
You are perfectly correct... At least it explains why I had bad performances on MPI + GPUS.

Thanks

**Comment by JCfrW** [comment]
OK, it is correct... Need to see if it works on ATS now !
